// <auto-generated />
using System;
using InParadise.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InParadise.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307084523_AmenityTBL")]
    partial class AmenityTBL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InParadise.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "استخر خصوصی",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "فر آشپزخانه",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "بالکن خصوصی",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "یک تخت بزرگ به همراه یک مبل تختخواب شو",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "استخز اختصاصی با سقوط آزاد",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "آشپز خانه مجهز",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "بالکن اختصاصی",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "تخت دو نفره",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "استخر خصوصی",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "جکوزی",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "بالکن اختصاصی",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("InParadise.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "ویلای رویال",
                            Occupancy = 4,
                            Price = 200L,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "ویلای استخردار ممتاز",
                            Occupancy = 4,
                            Price = 300L,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "ویلای لوکس با استخر",
                            Occupancy = 4,
                            Price = 400L,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("InParadise.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("NumberOfVilla")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("NumberOfVilla");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            NumberOfVilla = 101,
                            VillaId = 1
                        },
                        new
                        {
                            NumberOfVilla = 102,
                            VillaId = 1
                        },
                        new
                        {
                            NumberOfVilla = 103,
                            VillaId = 1
                        },
                        new
                        {
                            NumberOfVilla = 201,
                            VillaId = 2
                        },
                        new
                        {
                            NumberOfVilla = 202,
                            VillaId = 2
                        },
                        new
                        {
                            NumberOfVilla = 203,
                            VillaId = 2
                        },
                        new
                        {
                            NumberOfVilla = 301,
                            VillaId = 3
                        },
                        new
                        {
                            NumberOfVilla = 302,
                            VillaId = 3
                        },
                        new
                        {
                            NumberOfVilla = 303,
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("InParadise.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("InParadise.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("InParadise.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("InParadise.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
